# -*- coding: utf-8 -*-
"""CIS556_clean.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjpMgvQG1Tge6M6mbrJJR51pZ9NcZYqJ
"""

import pandas as pd
import numpy as np

#load data into dataframes
#Order Data
df_orderlist = pd.read_csv('/content/OrderList.csv')

#Freight Rates
df_freightrates = pd.read_csv('/content/FreightRates.csv')

#PlantPorts

df_plantports = pd.read_csv('/content/PlantPorts.csv')

#ProductsPerPlant

df_productperplant = pd.read_csv('/content/ProductsPerPlant.csv')

#Customer

df_vmicustomers = pd.read_csv('/content/VmiCustomers.csv')

## Warehouse/Plant Data
df_warehouse = pd.read_csv('/content/Warehouse.csv')

"""# Checking for nulls in each tables"""

#Order Data
print ("Checking order data for nulls: \n", df_orderlist.isnull().sum(),"\n")

#Freight Rates
print ("Checking freight rates data for nulls: \n", df_freightrates.isnull().sum(),"\n")

#Plant ports
print ("Checking plant ports table for nulls: \n", df_plantports.isnull().sum(),"\n")

#Products per plant 
print ("Checking products per plant table for nulls: \n", df_productperplant.isnull().sum(),"\n")

#Products per plant 
print ("Checking Warehouse table for nulls: \n", df_warehouse.isnull().sum(),"\n")

print ("Checking Customer table for nulls: \n", df_vmicustomers.isnull().sum(),"\n")

"""There are no nulls in the values in any of the tables

# Checking Statistical Distribution of each columns in each table and handling outliers if (any)
"""

print ("Checking  Distribution of columns for Order Table: \n", df_orderlist.describe(),"\n")

print ("Checking  Distribution of columns for Freight Rate Table: \n", df_freightrates.describe(),"\n")

print ("Checking  Distribution of columns for Plant Ports Table: \n", df_plantports.describe(),"\n")

print ("Checking  Distribution of columns for Products per plant Table: \n", df_productperplant.describe(),"\n")

print ("Checking  Distribution of columns for Warehouse Table: \n", df_warehouse.describe(),"\n")

print ("Checking  Distribution of columns for Customer Table: \n", df_vmicustomers.describe(),"\n")